POST http://0.0.0.0:9696/predict
Content-Type: application/json

{
    "person_age": 22,
    "person_income": 59000,
    "person_home_ownership": "RENT",
    "person_emp_length": 123,
    "loan_intent": "PERSONAL",
    "loan_grade": "D",
    "loan_amnt": 35000,
    "loan_int_rate": 16.02,
    "loan_percent_income": 0.59,
    "cb_person_default_on_file": "Y",
    "cb_person_cred_hist_length": 3
}

# POST http://localhost:9696/predict
# POST http://0.0.0.0:9696/predict
# loan_status: 1
# GET https://api.example.com/users

# @header Authorization: Bearer <token>